openapi: 3.0.3
info:
  title: Five Stars Rental Inventory API
  description: |
    # About Us
    ***Five Stars Rental*** is an online car rental platform with a massive variety of vehicles in stock. Whether you're looking for a sedan for city driving, an SUV for a weekend getaway, or a luxury vehicle for a special occasion, our developer-friendly interface gives you full access to vehicle availability and booking management.
  termsOfService: https://fivestarsrental.com/terms/
  contact:
    name: API support
    url: https://fivestarsrental.com/support/
    email: support@fivestarsrental.com
  license:
    name: Five Stars Rental License
    url: https://fivestarsrental.com/license/
  version: "1.0"
servers:
  - url: https://cfaba586-1ae7-4a52-82e9-43ac2e9772a8.mock.pstmn.io
    description: Postman mock server
tags:
  - name: Categories
    description: Categories-related operations
  - name: Bookings
    description: Bookings-related operations
security:
  - BasicAuth: []
  - BearerAuth: []
  - ApiKeyAuth: [] 
  - oAuth2AuthCode:
    - read
    - write
    - admin

paths:
  /categories:
    get:
      tags:
        - Categories
      summary: Get all categories
      operationId: getCategories
      description: Retrieves a list of all rental categories available at Five Stars Rental.
      responses:
        '200':
          description: A list of rental categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
              example:
                - categoryId: 1
                  name: sedan
                - categoryId: 2
                  name: coupe
                - categoryId: 3
                  name: SUV
                - categoryId: 4
                  name: crossover
                - categoryId: 5
                  name: minivan
                - categoryId: 6
                  name: wagon
                - categoryId: 7
                  name: convertible
                - categoryId: 8
                  name: exotic
          links:
            CategoryDetails:
              operationId: getCategoryById
              parameters:
                categoryId: '$response.body#/CategoryId'  
              description: Link to get detailed info for one of these categories.
            RentalsByCategory:
              operationId: getRentalsByCategoryId
              parameters:
                categoryId: '$response.body#/CategoryId'  
              description: Link to get a list of rentals for one of these categories.
            BookByCategory:
              operationId: bookRequest
              parameters:
                categoryId: '$response.body#/CategoryId'  
              description: Link to start a booking by category ID.
        '500':
          $ref: '#/components/responses/ServerError'

  /categories/{categoryId}:
    get:
      tags:
        - Categories
      summary: Get a category by ID
      operationId: getCategoryById
      description: Returns details of a specific vehicle category.
      parameters:
        - $ref: '#/components/parameters/CategoryId'
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
              examples:
                sedanExamples:
                  summary: Summary of category 1
                  value:
                    id: 1
                    name: sedan
                    description: four-door tourers
                    totalCars: 393
                    available: 288
                    dailyRate:
                      min: 30.00
                      max: 90.00
                coupeExamples:
                  summary: Summary of category 2
                  value:
                     id: 2
                     name: coupe
                     description: two-door tourers
                     totalCars: 212
                     available: 128
                     dailyRate: 
                      min: 25.00
                      max: 120.00
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /categories/{categoryId}/rentals:
    get:
      tags:
        - Categories
      summary: Get a list of rentals by category
      operationId: getRentalsByCategoryId
      description: Returns all rental vehicles in the specified category.
      parameters:
        - $ref: '#/components/parameters/CategoryId'
      responses:
        '200':
          description: A list of rental vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rental'
              examples:
                sedanExamples:
                  summary: Rentals in category 1 
                  description: Sample rentals for sedans
                  value:
                    - rentalId: 1008
                      brand: Toyota
                      model: Camry
                      year: 2024
                    - rentalId: 1009
                      brand: Honda
                      model: Accord
                      year: 2023
                    - rentalId: 1010
                      brand: Nissan
                      model: Altima
                      year: 2022
                coupeExamples:
                  summary: Rentals in category 2
                  description: sample rentals for coupes
                  value:
                    - rentalId: 2001
                      brand: BMW
                      model: 230i
                      year: 2023
                    - rentalId: 2002
                      brand: Honda 
                      model: Civic Coupe
                      year: 2019
                    - rentalId: 2003
                      brand: Subaru
                      model: BR-Z
                      year: 2022
          links:
            RentalDetails:
              operationId: getRentalsDetails
              parameters:
                categoryId: '$response.body#/RentalId'  
              description: Link to get detailed info for the returned rental.
            BookByRental:
              operationId: bookRequest
              parameters:
                categoryId: '$response.body#/RentalId'  
              description: Link to start a booking by rental ID.
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /rentals/{rentalId}:
    get:
      tags:
        - Categories
      summary: Get rental details
      operationId: getRentalsDetails
      description: Returns detailed information about a specific rental.
      parameters:
        - $ref: '#/components/parameters/RentalId'
      responses:
        '200':
          description: Rental details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalDetails'
              example:
                rentalId: 5019
                categoryId: 5
                brand: Mercedes
                model: Metris
                year: 2023
                transmission: automatic
                color: Black
                dailyRate: 75
                status: maintenance
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /book:
    post:
      tags:
        - Bookings
      operationId: bookRequest
      summary: Create a new booking
      description: Creates a new rental booking.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBookingRequest'
      responses:
        '201':
          description: Booking successfully processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookingId:
                    type: integer
                  brand:
                    type: string
                  model:
                    type: string
                  year: 
                    type: integer
                    format: date
                  transmission:
                    type: string
                    enum: [automatic, manual]
                  dailyRate:
                    type: integer
                  message:
                    type: string
              example:
                bookingId: 92379
                brand: Nissan
                model: Sentra
                year: 2024
                transmission: automatic
                dailyRate: 29
                message: Booking successful
          links:
            CheckBookingDetails:
              operationId: checkBookingId
              description: Get booking details by ID.
              parameters:
                bookingId: '$response.body#/bookingId'
            UpdateBooking:
              operationId: updateBookingById
              description: Update booking details by ID.
              parameters:
                bookingId: '$response.body#/bookingId'
            CancelBooking:
              operationId: cancelBookingById
              description: Cancel the booking by ID.
              parameters:
                bookingId: '$response.body#/bookingId'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Conflict — rental already booked for that date range
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Rental is unavailable for the selected dates.
        '500':
          $ref: '#/components/responses/ServerError'

  /book/{bookingId}:
    get:
      operationId: checkBookingId
      tags:
        - Bookings
      summary: Get booking details
      description: Retrieve booking details by ID.
      parameters:
        - $ref: '#/components/parameters/BookingId'
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
              example:
                bookingId: 58124
                customerName: Jane Doe 
                categoryId: 3
                rentalId: 3009
                brand: Ford
                model: Explorer
                year: 2022
                transmission: automatic
                dailyRate: 62
                startDate: 2025-07-22
                endDate: 2025-07-24
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'


    put:
      tags:
        - Bookings
      summary: Update a booking
      operationId: updateBookingById
      description: Updates an existing booking.
      parameters:
        - $ref: '#/components/parameters/BookingId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookingRequest'
      responses:
        '200':
          description: Booking successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookingId:
                    type: integer
                    example: 73302
                  brand: 
                    type: string
                    example: Acura
                  model: 
                    type: string
                    example: Integra
                  year: 
                    type: integer
                    format: year
                    example: 2025
                  transmission:
                    type: string
                    enum: [automatic, manual]
                    example: automatic
                  dailyRate:
                    type: integer
                    example: 44
                  message:
                    type: string
                    example: Booking updated successfully.
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Conflict — updated dates or rental not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Requested rental is unavailable for the new date range.
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Bookings
      summary: Cancel a booking
      operationId: cancelBookingById
      description: Cancels an existing booking.
      parameters:
        - $ref: '#/components/parameters/BookingId'
      responses:
        '200':
          description: Booking successfully canceled
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Booking canceled successfully.
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
                    
components:

  schemas:

    CategoryBase:
      type: object
      properties:
        CategoryId:
          type: integer
        name:
          type: string
      required:
        - id
        - name

    Category:
      allOf:
        - $ref: '#/components/schemas/CategoryBase'

    Rental:
      type: object
      properties:
        rentalId:
          type: integer
        brand:
          type: string
        model:
          type: string
        year:
          type: integer
          format: year
          
      
    RentalDetails:
      type: object
      properties:
        rentalId:
          type: integer
        categoryId:
          type: integer
        brand:
          type: string
        model:
          type: string
        year:
          type: integer
          format: year
        transmission:
          type: string
          enum: [automatic, manual]
        color:
          type: string
        dailyRate:
          type: integer
        status:
          type: string
          enum: [available, maintenance, rented]

    Booking:
      type: object
      properties:
        bookingId:
          type: integer
        customerName:
          type: string
        categoryId:
          type: integer
        rentalId:
          type: integer
        brand:
          type: string
        model:
          type: string
        year:
          type: integer
          format: year
        transmission:
          type: string
          enum: [automatic, manual]
        dailyRate:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    StandardBooking:
      type: object
      properties:
        bookingType:
          type: string
          enum: [By rental ID]
        customerName:
          type: string
        rentalId:
          type: integer
        rentalStartDate:
          type: string
          format: date
        rentalEndDate:
          type: string
          format: date
      required:
        - customerName
        - categoryId
        - rentalId
        - rentalStartDate
        - rentalEndDate

    FlexibleBooking:
      type: object
      properties:
        bookingType:
          type: string
          enum: [By category ID]
        customerName:
          type: string
        categoryId:
          type: integer
        preferredStart:
          type: string
          format: date
        preferredEnd:
          type: string
          format: date
      required:
        - customerName
        - categoryId
        - preferredStart
        - preferredEnd

    NewBookingRequest:
      oneOf:
        - $ref: '#/components/schemas/StandardBooking'
        - $ref: '#/components/schemas/FlexibleBooking'
      discriminator:
        propertyName: bookingType

    UpdateBookingRequest:
      type: object
      properties:
        customerName:
          type: string
          example: John Doe
        categoryId:
          type: integer
          example: 2
        rentalId:
          type: integer
          example: 2088
        startDate:
          type: string
          format: date
          example: 2025-08-01
        endDate:
          type: string
          format: date
          example: 2025-08-07
      required:
        - customerName
        - categoryId
        - rentalId
        - startDate
        - endDate

  parameters:
  
    CategoryId:
      name: categoryId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
        maximum: 8
      description: |
        Category ID:
        - 1 = sedans (rentalId 1000–1999)
        - 2 = coupes (rentalId 2000–2999)
        - 3 = SUVs (rentalId 3000–3999)
        - 4 = Crossovers (rentalId 4000–4999)
        - 5 = Minivans (rentalId 5000–5999)
        - 6 = Wagons (rentalId 6000–6999)
        - 7 = Convertibles (rentalId 7000–7999)
        - 8 = Exotics (rentalId 8000–8999)

    RentalId:
      name: rentalId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1001
        maximum: 4999
      description: Rental ID must be within the valid range for its category.

    BookingId:
      name: bookingId
      in: path
      required: true
      schema:
        type: integer
      description: The unique ID of the booking.

  responses:
  
    BookingSuccess:
      description: Booking successfully processed
      content:
        application/json:
          schema:
            type: object
            properties:
              bookingId:
                type: integer
              brand:
                type: string
              model:
                type: string
              year: 
                type: integer
                format: date
              transmission:
                type: string
                enum: [automatic, manual]
              dailyRate:
                type: integer
              message:
                type: string
          example:
            bookingId: 92379
            brand: Nissan
            model: Sentra
            year: 2024
            transmission: automatic
            dailyRate: 29
            message: Booking successful
            
    ValidationError:
      description: Input validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example: 
              message: Input validation failed.

    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example: 
              message: The specified resource was not found.


    ServerError:
      description: An unexpected error occurred on the server
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: Internal server error. Please try again later.
              
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    oAuth2AuthCode:
      type: oauth2
      flows:
        authorizationCode: 
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/api/oauth.access
          scopes:
            read: Read only access
            write: Read Write access
            admin: Admin access 

